export enum VRMBlendShapePresetName {
  A = 'a',
  Angry = 'angry',
  Blink = 'blink',
  BlinkL = 'blink_l',
  BlinkR = 'blink_r',
  E = 'e',
  Fun = 'fun',
  I = 'i',
  Joy = 'joy',
  Lookdown = 'lookdown',
  Lookleft = 'lookleft',
  Lookright = 'lookright',
  Lookup = 'lookup',
  Neutral = 'neutral',
  O = 'o',
  Sorrow = 'sorrow',
  U = 'u',
  Unknown = 'unknown',
}
