export declare const VRMExpressionPresetName: {
    readonly Aa: "aa";
    readonly Ih: "ih";
    readonly Ou: "ou";
    readonly Ee: "ee";
    readonly Oh: "oh";
    readonly Blink: "blink";
    readonly Happy: "happy";
    readonly Angry: "angry";
    readonly Sad: "sad";
    readonly Relaxed: "relaxed";
    readonly LookUp: "lookUp";
    readonly Surprised: "surprised";
    readonly LookDown: "lookDown";
    readonly LookLeft: "lookLeft";
    readonly LookRight: "lookRight";
    readonly BlinkLeft: "blinkLeft";
    readonly BlinkRight: "blinkRight";
    readonly Neutral: "neutral";
};
export type VRMExpressionPresetName = typeof VRMExpressionPresetName[keyof typeof VRMExpressionPresetName];
