#!/bin/bash

readonly DEV='dev'

while read local_ref local_sha1 remote_ref remote_sha1
do
  if [[ "${remote_ref##refs/heads/}" = $DEV ]]; then
    echo -e "Do not push to dev branch"
    exit 1
  fi
done